create table notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  noteName text,
  folderId INTEGER REFERENCES folders(id) on delete restrict not null,
  modified timestamp default now(),
  content text
);